#!/usr/bin/env node
// GENERATED by scripts/build-hooks.mjs from hooks/src/ — do not edit by hand.

// plugins/claude/hooks/src/reconcile.entry.mjs
import fs from "node:fs";
import path from "node:path";

// packages/core/dist/task/statuses.js
var STATUSES = [
  "draft",
  "queued",
  "plan-review",
  "in-progress",
  "in-review",
  "completed",
  "abandoned"
];

// packages/core/dist/task/audit.js
var KNOWN_NON_STATUS_DIRS = ["runs"];
var hasAnomalies = (a) => a.unknownDirs.length > 0 || a.strayFiles.length > 0 || a.duplicates.length > 0;
var formatAnomalies = (a, tasksDir) => [
  ...a.unknownDirs.map((d) => `unknown folder ${tasksDir}/${d}/ \u2014 not a status folder; a confused agent likely created it`),
  ...a.strayFiles.map((f) => `stray task file ${f} \u2014 outside every status folder, invisible to the loop`),
  ...a.duplicates.map((d) => `duplicate task "${d.id}" in ${d.statuses.join(", ")} \u2014 resolve manually (keep one, abandon the rest)`)
];
var isMarkdown = (name) => name.toLowerCase().endsWith(".md");
var listDir = async (client, directory, rel) => {
  try {
    const res = await client.file.list({ query: { path: rel, directory } });
    return res.data ?? [];
  } catch {
    return [];
  }
};
var auditBacklog = async (client, directory, tasksDir) => {
  const root = await listDir(client, directory, tasksDir);
  const unknownDirs = root.filter((n) => n.type === "directory" && !n.name.startsWith(".")).map((n) => n.name).filter((name) => !STATUSES.includes(name) && !KNOWN_NON_STATUS_DIRS.includes(name)).sort();
  const strayFiles = root.filter((n) => n.type === "file" && isMarkdown(n.name)).map((n) => `${tasksDir}/${n.name}`);
  for (const dir of unknownDirs) {
    const nodes = await listDir(client, directory, `${tasksDir}/${dir}`);
    for (const n of nodes) {
      if (n.type === "file" && isMarkdown(n.name))
        strayFiles.push(`${tasksDir}/${dir}/${n.name}`);
    }
  }
  const seen = /* @__PURE__ */ new Map();
  for (const status of STATUSES) {
    const nodes = await listDir(client, directory, `${tasksDir}/${status}`);
    for (const n of nodes) {
      if (n.type !== "file" || !isMarkdown(n.name))
        continue;
      const id = n.name.replace(/\.md$/i, "");
      seen.set(id, [...seen.get(id) ?? [], status]);
    }
  }
  const duplicates = [...seen.entries()].filter(([, statuses]) => statuses.length > 1).map(([id, statuses]) => ({ id, statuses })).sort((a, b) => a.id.localeCompare(b.id));
  return { unknownDirs, strayFiles, duplicates };
};

// plugins/claude/hooks/src/reconcile.entry.mjs
var wasInterrupted = (body) => {
  const lastStart = body.lastIndexOf("> BUILD started");
  if (lastStart === -1) return false;
  return body.lastIndexOf("> BUILD finished") < lastStart;
};
var read = () => new Promise((resolve) => {
  let s = "";
  process.stdin.on("data", (c) => s += c).on("end", () => resolve(s));
});
var fsClient = {
  file: {
    list: async ({ query: { path: rel, directory } }) => {
      try {
        const entries = fs.readdirSync(path.join(directory, rel), { withFileTypes: true });
        return { data: entries.map((e) => ({ type: e.isDirectory() ? "directory" : "file", name: e.name })) };
      } catch {
        return { data: [] };
      }
    },
    read: async () => ({ data: null })
  },
  app: { log: async () => void 0 }
};
var main = async () => {
  let input = {};
  try {
    input = JSON.parse(await read());
  } catch {
  }
  const cwd = input.cwd || process.cwd();
  let tasksDir = "docs/tasks";
  try {
    const cfg = JSON.parse(fs.readFileSync(path.join(cwd, ".agentic-loop.json"), "utf8"));
    if (typeof cfg.tasksDir === "string" && cfg.tasksDir) tasksDir = cfg.tasksDir;
  } catch {
  }
  const notes = [];
  const inProgress = path.join(cwd, tasksDir, "in-progress");
  try {
    for (const name of fs.readdirSync(inProgress)) {
      if (!name.endsWith(".md")) continue;
      const body = fs.readFileSync(path.join(inProgress, name), "utf8");
      if (wasInterrupted(body)) notes.push(name.replace(/\.md$/, ""));
    }
  } catch {
  }
  let snapshots = [];
  try {
    snapshots = fs.readdirSync(path.join(cwd, tasksDir, "runs")).filter((n) => n.endsWith(".state.json")).map((n) => n.replace(/\.state\.json$/, ""));
  } catch {
  }
  let planClaims = [];
  try {
    planClaims = fs.readdirSync(path.join(cwd, tasksDir, "queued", ".claims"));
  } catch {
  }
  const anomalies = await auditBacklog(fsClient, cwd, tasksDir);
  const lines = [];
  if (notes.length) lines.push(`agentic-loop: interrupted task(s) in ${tasksDir}/in-progress: ${notes.join(", ")} \u2014 run \`/agentic-loop:engineering recover <id>\` to resume.`);
  if (snapshots.length) lines.push(`agentic-loop: loop state snapshot(s) present: ${snapshots.join(", ")} \u2014 \`/agentic-loop:engineering recover <id>\` resumes at the exact stage.`);
  if (planClaims.length) lines.push(`agentic-loop: leftover plan-claim marker(s) in ${tasksDir}/queued/.claims: ${planClaims.join(", ")} \u2014 a prior run died mid-PLAN; \`loop_doctor\` (fix:true) releases stale markers so the task can be claimed again.`);
  if (hasAnomalies(anomalies)) {
    for (const line of formatAnomalies(anomalies, tasksDir)) lines.push(`agentic-loop: ${line} \u2014 \`loop_doctor\` reports and repairs.`);
  }
  if (!lines.length) return process.exit(0);
  process.stdout.write(
    JSON.stringify({ hookSpecificOutput: { hookEventName: "SessionStart", additionalContext: lines.join("\n") } })
  );
  process.exit(0);
};
main();
