#!/usr/bin/env node
// GENERATED by scripts/build-hooks.mjs from hooks/src/ — do not edit by hand.

// plugins/claude/hooks/src/reconcile.entry.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// packages/core/dist/task/statuses.js
var STATUSES = [
  "draft",
  "queued",
  "plan-review",
  "in-progress",
  "in-review",
  "completed",
  "abandoned"
];

// packages/core/dist/task/audit.js
var KNOWN_NON_STATUS_DIRS = ["runs"];
var hasAnomalies = (a) => a.unknownDirs.length > 0 || a.strayFiles.length > 0 || a.duplicates.length > 0;
var formatAnomalies = (a, tasksDir) => [
  ...a.unknownDirs.map((d) => `unknown folder ${tasksDir}/${d}/ \u2014 not a status folder; a confused agent likely created it`),
  ...a.strayFiles.map((f) => `stray task file ${f} \u2014 outside every status folder, invisible to the loop`),
  ...a.duplicates.map((d) => `duplicate task "${d.id}" in ${d.statuses.join(", ")} \u2014 resolve manually (keep one, abandon the rest)`)
];
var isMarkdown = (name) => name.toLowerCase().endsWith(".md");
var listDir = async (client, directory, rel) => {
  try {
    const res = await client.file.list({ query: { path: rel, directory } });
    return res.data ?? [];
  } catch {
    return [];
  }
};
var auditBacklog = async (client, directory, tasksDir, statuses = STATUSES) => {
  const root = await listDir(client, directory, tasksDir);
  const unknownDirs = root.filter((n) => n.type === "directory" && !n.name.startsWith(".")).map((n) => n.name).filter((name) => !statuses.includes(name) && !KNOWN_NON_STATUS_DIRS.includes(name)).sort();
  const strayFiles = root.filter((n) => n.type === "file" && isMarkdown(n.name)).map((n) => `${tasksDir}/${n.name}`);
  for (const dir of unknownDirs) {
    const nodes = await listDir(client, directory, `${tasksDir}/${dir}`);
    for (const n of nodes) {
      if (n.type === "file" && isMarkdown(n.name))
        strayFiles.push(`${tasksDir}/${dir}/${n.name}`);
    }
  }
  const seen = /* @__PURE__ */ new Map();
  for (const status of statuses) {
    const nodes = await listDir(client, directory, `${tasksDir}/${status}`);
    for (const n of nodes) {
      if (n.type !== "file" || !isMarkdown(n.name))
        continue;
      const id = n.name.replace(/\.md$/i, "");
      seen.set(id, [...seen.get(id) ?? [], status]);
    }
  }
  const duplicates = [...seen.entries()].filter(([, statuses2]) => statuses2.length > 1).map(([id, statuses2]) => ({ id, statuses: statuses2 })).sort((a, b) => a.id.localeCompare(b.id));
  return { unknownDirs, strayFiles, duplicates };
};

// plugins/claude/hooks/src/dialect.mjs
var DIALECTS = {
  claude: {
    stageMarkerFile: ".stage.json",
    // Claude Code surfaces plugin MCP tools under a second, plugin-bundled
    // alias; Qwen has only the one registration.
    verdictAliases: "mcp__agentic-workflow__workflow_verdict or, plugin-bundled, mcp__plugin_agentic-workflow_agentic-workflow__workflow_verdict",
    bash: ["Bash"],
    write: ["Edit", "Write", "NotebookEdit"],
    spawnTool: "Task tool",
    // Whether the host's spawn tool takes a per-call model. False on Qwen: the
    // model is baked into the installed agent file, so telling the orchestrator
    // to "set `model`" would name a parameter that does not exist.
    conveysSpawnModel: true,
    // The tool names that spawn a subagent, for the PreToolUse stamp. `Task` was
    // renamed `Agent` in Claude Code 2.1.63 and is still accepted as an alias, so
    // both are matched — a rename that silently stopped matching would disable
    // the model binding without failing anything.
    spawn: ["Agent", "Task"],
    // What the host prepends to a plugin agent's name in `subagent_type`
    // (`agentic-workflow:workflow-build`). Stripped before the name is checked
    // against the agents this plugin ships.
    agentPrefixes: ["agentic-workflow:", "mcp__plugin_agentic-workflow_agentic-workflow__"],
    installer: "plugins/claude/install.sh"
  },
  qwen: {
    stageMarkerFile: ".stage-qwen.json",
    verdictAliases: "mcp__agentic-workflow__workflow_verdict",
    bash: ["run_shell_command"],
    write: ["write_file", "edit", "replace", "notebook_edit"],
    spawnTool: "`agent` tool",
    conveysSpawnModel: false,
    // Empty on purpose, and unreachable: `conveysSpawnModel: false` already
    // stops the stamp before it looks at a tool name, because Qwen's `agent`
    // tool has no `model` parameter to stamp into.
    spawn: [],
    agentPrefixes: [],
    installer: "./install.sh qwen"
  }
};
var KNOWN_HOSTS = Object.keys(DIALECTS);
var hostFor = (env = process.env) => {
  const raw = env.AGENTIC_WORKFLOW_HOST || void 0;
  if (raw === void 0) return "claude";
  return raw in DIALECTS ? raw : null;
};
var dialectFor = (host) => host && host in DIALECTS ? DIALECTS[host] : null;

// plugins/claude/hooks/src/reconcile.entry.mjs
var lastMarkerIndex = (body, marker) => {
  for (let idx = body.lastIndexOf(marker); idx !== -1; idx = body.lastIndexOf(marker, idx - 1)) {
    if (idx === 0 || body[idx - 1] === "\n") return idx;
  }
  return -1;
};
var wasInterrupted = (body) => {
  const anchor = lastMarkerIndex(body, "> Plan approved");
  const window = anchor === -1 ? body : body.slice(anchor);
  const lastStart = lastMarkerIndex(window, "> BUILD started");
  if (lastStart === -1) return false;
  return lastMarkerIndex(window, "> BUILD finished") < lastStart;
};
var read = () => new Promise((resolve) => {
  let s = "";
  process.stdin.on("data", (c) => s += c).on("end", () => resolve(s));
});
var fsClient = {
  file: {
    list: async ({ query: { path: rel, directory } }) => {
      try {
        const entries = fs.readdirSync(path.join(directory, rel), { withFileTypes: true });
        return { data: entries.map((e) => ({ type: e.isDirectory() ? "directory" : "file", name: e.name })) };
      } catch {
        return { data: [] };
      }
    },
    read: async () => ({ data: null })
  },
  app: { log: async () => void 0 }
};
var main = async () => {
  let input = {};
  try {
    input = JSON.parse(await read());
  } catch {
  }
  const cwd = input.cwd || process.cwd();
  let tasksDir = "docs/tasks";
  try {
    const cfg = JSON.parse(fs.readFileSync(path.join(cwd, ".agentic-workflow.json"), "utf8"));
    if (typeof cfg.tasksDir === "string" && cfg.tasksDir) tasksDir = cfg.tasksDir;
  } catch {
  }
  const notes = [];
  const inProgress = path.join(cwd, tasksDir, "in-progress");
  try {
    for (const name of fs.readdirSync(inProgress)) {
      if (!name.endsWith(".md")) continue;
      const body = fs.readFileSync(path.join(inProgress, name), "utf8");
      if (wasInterrupted(body)) notes.push(name.replace(/\.md$/, ""));
    }
  } catch {
  }
  let snapshots = [];
  try {
    snapshots = fs.readdirSync(path.join(cwd, tasksDir, "runs")).filter((n) => n.endsWith(".state.json")).map((n) => n.replace(/\.state\.json$/, ""));
  } catch {
  }
  let planClaims = [];
  try {
    planClaims = fs.readdirSync(path.join(cwd, tasksDir, "queued", ".claims"));
  } catch {
  }
  const anomalies = await auditBacklog(fsClient, cwd, tasksDir);
  const pluginRoot = process.env.AGENTIC_WORKFLOW_PLUGIN_ROOT || process.env.CLAUDE_PLUGIN_ROOT || path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
  const serverBuilt = fs.existsSync(path.join(pluginRoot, "mcp-server", "dist", "server.js"));
  const lines = [];
  if (!serverBuilt)
    lines.push(
      `agentic-workflow: MCP server not built (mcp-server/dist/server.js missing) \u2014 gates and loop tools will not work. Run ${dialectFor(hostFor())?.installer ?? "the installer"}, then restart the session.`
    );
  if (notes.length) lines.push(`agentic-workflow: interrupted task(s) in ${tasksDir}/in-progress: ${notes.join(", ")} \u2014 run \`/agentic-workflow:engineering recover <id>\` to resume.`);
  if (snapshots.length) lines.push(`agentic-workflow: loop state snapshot(s) present: ${snapshots.join(", ")} \u2014 \`/agentic-workflow:engineering recover <id>\` resumes at the exact stage.`);
  if (planClaims.length) lines.push(`agentic-workflow: leftover plan-claim marker(s) in ${tasksDir}/queued/.claims: ${planClaims.join(", ")} \u2014 a prior run died mid-PLAN; \`workflow_doctor\` (fix:true) releases stale markers so the task can be claimed again.`);
  if (hasAnomalies(anomalies)) {
    for (const line of formatAnomalies(anomalies, tasksDir)) lines.push(`agentic-workflow: ${line} \u2014 \`workflow_doctor\` reports and repairs.`);
  }
  if (!lines.length) return process.exit(0);
  process.stdout.write(
    JSON.stringify({ hookSpecificOutput: { hookEventName: "SessionStart", additionalContext: lines.join("\n") } })
  );
  process.exit(0);
};
main();
