#!/usr/bin/env node
/**
 * Bundle the Claude plugin's hook sources (plugins/claude/hooks/src/*.entry.mjs)
 * into the self-contained .mjs files hooks.json runs. Hooks execute under bare
 * `node` from a possibly-copied plugin dir with no node_modules, so anything
 * they share with @agentic-workflow/core must be INLINED, not imported — esbuild
 * bundles core's built dist/ into the output.
 *
 * Outputs are checked in; CI fails when they drift from their sources
 * (`node scripts/build-hooks.mjs && git diff --exit-code`).
 */
import { build } from "esbuild"
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const SRC = path.join(ROOT, "plugins", "claude", "hooks", "src")
const OUT = path.join(ROOT, "plugins", "claude", "hooks")

const entries = fs.readdirSync(SRC).filter((f) => f.endsWith(".entry.mjs"))
if (entries.length === 0) {
  console.error("build-hooks: no *.entry.mjs sources found")
  process.exit(1)
}

for (const entry of entries) {
  const outfile = path.join(OUT, entry.replace(/\.entry\.mjs$/, ".mjs"))
  await build({
    entryPoints: [path.join(SRC, entry)],
    outfile,
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node20",
    banner: {
      js: "// GENERATED by scripts/build-hooks.mjs from hooks/src/ — do not edit by hand.",
    },
    legalComments: "none",
  })
  console.log(`build-hooks: ${path.relative(ROOT, outfile)}`)
}
