#!/usr/bin/env node
// GENERATED by scripts/build-hooks.mjs from hooks/src/ — do not edit by hand.

// plugins/claude/hooks/gate-command.mjs
import { spawnSync } from "node:child_process";
import fs2 from "node:fs";
import path2 from "node:path";
import { fileURLToPath } from "node:url";

// plugins/claude/hooks/gate-parse.mjs
var VERB = "(approve-plan|replan|approve)";
var SENTINEL = new RegExp(`GATE-DISPATCH:\\s*${VERB}\\b[ \\t]*(\\S+)?[ \\t]*(.*)$`, "im");
var CMD = "\\/(?:agentic-workflow:)?engineering(?![-\\w])";
var AT_START = "^\\s*";
var APPROVE = new RegExp(`${AT_START}${CMD}\\s+approve(?!-)\\b[ \\t]*(.*)`, "i");
var REPLAN = new RegExp(`${AT_START}${CMD}\\s+replan\\b[ \\t]*(.*)`, "i");
var RETASK = new RegExp(`${AT_START}${CMD}\\s+retask\\b[ \\t]*(.*)`, "i");
var REMOVE = new RegExp(`${AT_START}${CMD}\\s+remove\\b[ \\t]*(.*)`, "i");
var ABANDON = new RegExp(`${AT_START}${CMD}\\s+abandon\\b[ \\t]*(.*)`, "i");
var ANY_VERB = new RegExp(`${AT_START}${CMD}(\\s+\\S*)?`, "i");
var verbFor = (prompt) => {
  const match = String(prompt ?? "").match(ANY_VERB);
  if (!match) return null;
  return (match[1] || "").trim().toLowerCase() || "status";
};
var gateArgsFor = (prompt) => {
  const sentinel = prompt.match(SENTINEL);
  if (sentinel) {
    const id = (sentinel[2] || "").trim();
    if (!id) return { passThrough: true };
    const reason = (sentinel[3] || "").trim();
    return { argv: ["gate", sentinel[1], id, ...reason ? [reason] : []] };
  }
  const approve = prompt.match(APPROVE);
  if (approve) {
    const id = (approve[1] || "").trim().split(/\s+/).filter(Boolean)[0] || "";
    return { argv: ["gate", "approve-any", ...id ? [id] : []] };
  }
  const replan = prompt.match(REPLAN);
  if (replan) {
    const words = (replan[1] || "").trim().split(/\s+/).filter(Boolean);
    return { argv: ["gate", "reject-any", ...words] };
  }
  const retask = prompt.match(RETASK);
  if (retask) {
    const id = (retask[1] || "").trim().split(/\s+/).filter(Boolean)[0] || "";
    if (!id) return { passThrough: true };
    return { argv: ["gate", "retask", id], continueTurn: true };
  }
  const abandon = prompt.match(ABANDON);
  if (abandon) {
    const words = (abandon[1] || "").trim().split(/\s+/).filter(Boolean);
    const id = words[0] || "";
    if (!id) return { passThrough: true };
    return { argv: ["gate", "abandon", id, ...words.slice(1)] };
  }
  const remove = prompt.match(REMOVE);
  if (remove) {
    const words = (remove[1] || "").trim().split(/\s+/).filter(Boolean);
    const id = words.find((w) => !w.startsWith("-")) || "";
    if (!id) return { passThrough: true };
    const force = words.some((w) => w === "--force" || w === "-f");
    return { argv: ["gate", "remove", id, ...force ? ["--force"] : []] };
  }
  return null;
};

// plugins/claude/hooks/gate-result.mjs
var missingDistMessage = (label, installer = "plugins/claude/install.sh") => `agentic-workflow: can't run the "${label}" gate \u2014 the plugin is not built (mcp-server/dist/server.js is missing). Run ${installer}, then retry.`;
var decideGateOutcome = ({ distExists, spawnError, status, stdout }, label, installer) => {
  if (!distExists) return { action: "block", message: missingDistMessage(label, installer), ok: false };
  if (spawnError || status === null || status === void 0) return { action: "pass" };
  let parsed = null;
  try {
    const last = (stdout || "").trim().split("\n").filter(Boolean).pop();
    parsed = last ? JSON.parse(last) : null;
  } catch {
    parsed = null;
  }
  if (parsed && typeof parsed.message === "string") {
    return { action: "block", message: parsed.message, ok: parsed.ok === true };
  }
  if (status !== 0) return { action: "pass" };
  return { action: "block", message: `Gate ${label} done.`, ok: true };
};

// plugins/claude/hooks/src/dialect.mjs
var DIALECTS = {
  claude: {
    stageMarkerFile: ".stage.json",
    // Claude Code surfaces plugin MCP tools under a second, plugin-bundled
    // alias; Qwen has only the one registration.
    verdictAliases: "mcp__agentic-workflow__workflow_verdict or, plugin-bundled, mcp__plugin_agentic-workflow_agentic-workflow__workflow_verdict",
    bash: ["Bash"],
    write: ["Edit", "Write", "NotebookEdit"],
    spawnTool: "Task tool",
    // Whether the host's spawn tool takes a per-call model. False on Qwen: the
    // model is baked into the installed agent file, so telling the orchestrator
    // to "set `model`" would name a parameter that does not exist.
    conveysSpawnModel: true,
    // The tool names that spawn a subagent, for the PreToolUse stamp. `Task` was
    // renamed `Agent` in Claude Code 2.1.63 and is still accepted as an alias, so
    // both are matched — a rename that silently stopped matching would disable
    // the model binding without failing anything.
    spawn: ["Agent", "Task"],
    // What the host prepends to a plugin agent's name in `subagent_type`
    // (`agentic-workflow:workflow-build`). Stripped before the name is checked
    // against the agents this plugin ships.
    agentPrefixes: ["agentic-workflow:", "mcp__plugin_agentic-workflow_agentic-workflow__"],
    installer: "plugins/claude/install.sh"
  },
  qwen: {
    stageMarkerFile: ".stage-qwen.json",
    verdictAliases: "mcp__agentic-workflow__workflow_verdict",
    bash: ["run_shell_command"],
    write: ["write_file", "edit", "replace", "notebook_edit"],
    spawnTool: "`agent` tool",
    conveysSpawnModel: false,
    // Empty on purpose, and unreachable: `conveysSpawnModel: false` already
    // stops the stamp before it looks at a tool name, because Qwen's `agent`
    // tool has no `model` parameter to stamp into.
    spawn: [],
    agentPrefixes: [],
    installer: "./install.sh qwen"
  }
};
var KNOWN_HOSTS = Object.keys(DIALECTS);
var hostFor = (env = process.env) => {
  const raw = env.AGENTIC_WORKFLOW_HOST || void 0;
  if (raw === void 0) return "claude";
  return raw in DIALECTS ? raw : null;
};
var dialectFor = (host) => host && host in DIALECTS ? DIALECTS[host] : null;

// plugins/claude/hooks/verb-slice.mjs
import fs from "node:fs";
import path from "node:path";
var MARKER = /^<!--\s*(\/?)aw:verb\s+([a-z][a-z0-9|-]*)\s*-->$/;
var normalize = (verb) => String(verb ?? "").trim().toLowerCase() || null;
var tagLines = (body) => {
  const tagged = [];
  let open;
  for (const text of body.split("\n")) {
    const marker = MARKER.exec(text.trim());
    if (marker) {
      const [, closing, names] = marker;
      if (closing) {
        if (open !== names) return null;
        open = void 0;
      } else {
        if (open !== void 0) return null;
        open = names;
      }
      continue;
    }
    tagged.push({ text, verbs: open === void 0 ? null : open.split("|") });
  }
  return open === void 0 ? tagged : null;
};
var sliceForVerb = (body, verb) => {
  const tagged = tagLines(body);
  const wanted = normalize(verb);
  if (!tagged || !wanted) return null;
  const kept = tagged.filter((line) => line.verbs?.includes(wanted)).map((line) => line.text);
  if (kept.length === 0) return null;
  return kept.join("\n").replace(/\n{3,}/g, "\n\n").trim();
};
var verbContext = (pluginRoot, verb) => {
  const wanted = normalize(verb);
  if (!wanted) return null;
  let body;
  try {
    body = fs.readFileSync(path.join(pluginRoot, "verbs", "engineering.md"), "utf8");
  } catch {
    return null;
  }
  const slice = sliceForVerb(body, wanted) ?? sliceForVerb(body, "unknown");
  if (!slice) return null;
  return [
    `VERB INSTRUCTIONS \u2014 /agentic-workflow:engineering ${wanted}`,
    "",
    "This is the authoritative procedure for the verb you were asked to run.",
    "The command body you received is only the router. Follow this block, and do",
    "not act on any other verb's description.",
    "",
    slice
  ].join("\n");
};

// plugins/claude/hooks/gate-command.mjs
var read = () => new Promise((resolve) => {
  let s = "";
  process.stdin.on("data", (c) => s += c).on("end", () => resolve(s));
});
var passThrough = () => process.exit(0);
var augment = (message) => {
  process.stdout.write(JSON.stringify({ hookSpecificOutput: { hookEventName: "UserPromptSubmit", additionalContext: message } }));
  process.exit(0);
};
var block = (message) => {
  process.stdout.write(
    JSON.stringify({
      decision: "block",
      reason: message,
      hookSpecificOutput: { hookEventName: "UserPromptSubmit", additionalContext: message }
    })
  );
  process.exit(0);
};
var main = async () => {
  let input = {};
  try {
    input = JSON.parse(await read());
  } catch {
    return passThrough();
  }
  const prompt = input.prompt ?? input.user_input ?? input.userInput ?? "";
  const cwd = input.cwd || process.cwd();
  if (typeof prompt !== "string" || !prompt) return passThrough();
  const pluginRoot = process.env.AGENTIC_WORKFLOW_PLUGIN_ROOT || process.env.CLAUDE_PLUGIN_ROOT || path2.resolve(path2.dirname(fileURLToPath(import.meta.url)), "..");
  const injectVerb = () => {
    const context = verbContext(pluginRoot, verbFor(prompt));
    return context ? augment(context) : passThrough();
  };
  const dispatch = gateArgsFor(prompt);
  if (!dispatch) return injectVerb();
  if (dispatch.passThrough) return injectVerb();
  const args = dispatch.argv;
  const label = args.slice(1).join(" ");
  const serverJs = path2.join(pluginRoot, "mcp-server", "dist", "server.js");
  const distExists = fs2.existsSync(serverJs);
  const res = distExists ? spawnSync("node", [serverJs, ...args], {
    cwd,
    encoding: "utf8",
    env: { ...process.env, AGENTIC_WORKFLOW_DIR: process.env.AGENTIC_WORKFLOW_DIR ?? cwd }
  }) : {};
  const outcome = decideGateOutcome(
    { distExists, spawnError: res.error, status: res.status, stdout: res.stdout },
    label,
    dialectFor(hostFor())?.installer
  );
  if (outcome.action === "pass") return injectVerb();
  const message = outcome.message || `Gate ${label} ${outcome.ok ? "done" : "failed \u2014 see the backlog"}.`;
  if (dispatch.continueTurn && outcome.ok) {
    const context = verbContext(pluginRoot, verbFor(prompt), cwd);
    return augment(context ? `${message}

${context}` : message);
  }
  return block(message);
};
main();
