#!/usr/bin/env node
// GENERATED by scripts/build-hooks.mjs from hooks/src/ — do not edit by hand.

// plugins/claude/hooks/gate-command.mjs
import { spawnSync } from "node:child_process";
import fs2 from "node:fs";
import path2 from "node:path";
import { fileURLToPath } from "node:url";

// plugins/claude/hooks/gate-parse.mjs
var CMD = "\\/(?:agentic-workflow:)?engineering(?=\\s|$)";
var AT_START = "^\\s*";
var APPROVE = new RegExp(`${AT_START}${CMD}\\s+approve(?!-)\\b[ \\t]*(.*)`, "i");
var REPLAN = new RegExp(`${AT_START}${CMD}\\s+replan\\b[ \\t]*(.*)`, "i");
var RETASK = new RegExp(`${AT_START}${CMD}\\s+retask\\b[ \\t]*(.*)`, "i");
var REMOVE = new RegExp(`${AT_START}${CMD}\\s+remove\\b[ \\t]*(.*)`, "i");
var ABANDON = new RegExp(`${AT_START}${CMD}\\s+abandon\\b[ \\t]*(.*)`, "i");
var ANY_VERB = new RegExp(`${AT_START}${CMD}(\\s+\\S*)?`, "i");
var verbFor = (prompt) => {
  const match = String(prompt ?? "").match(ANY_VERB);
  if (!match) return null;
  const raw = (match[1] || "").trim().toLowerCase();
  return raw.replace(/^["'`]+/, "").replace(/["'`.,:;!?]+$/, "") || "status";
};
var unquote = (word) => word.replace(/^["'`]+/, "").replace(/["'`]+$/, "");
var gateArgsFor = (prompt) => {
  const approve = prompt.match(APPROVE);
  if (approve) {
    const id = unquote((approve[1] || "").trim().split(/\s+/).filter(Boolean)[0] || "");
    return { argv: ["gate", "approve-any", ...id ? [id] : []] };
  }
  const replan = prompt.match(REPLAN);
  if (replan) {
    const words = (replan[1] || "").trim().split(/\s+/).filter(Boolean);
    if (words.length) words[0] = unquote(words[0]);
    return { argv: ["gate", "reject-any", ...words] };
  }
  const retask = prompt.match(RETASK);
  if (retask) {
    const id = unquote((retask[1] || "").trim().split(/\s+/).filter(Boolean)[0] || "");
    if (!id) return { usage: "Usage: /agentic-workflow:engineering retask <id> [note]." };
    return { argv: ["gate", "retask", id], continueTurn: true };
  }
  const abandon = prompt.match(ABANDON);
  if (abandon) {
    const words = (abandon[1] || "").trim().split(/\s+/).filter(Boolean);
    const id = unquote(words[0] || "");
    if (!id) return { usage: "Usage: /agentic-workflow:engineering abandon <id> [reason]." };
    return { argv: ["gate", "abandon", id, ...words.slice(1)] };
  }
  const remove = prompt.match(REMOVE);
  if (remove) {
    const words = (remove[1] || "").trim().split(/\s+/).filter(Boolean);
    const id = unquote(words.find((w) => !w.startsWith("-")) || "");
    if (!id) return { usage: "Usage: /agentic-workflow:engineering remove <id> [--force]." };
    const force = words.some((w) => w === "--force" || w === "-f");
    return { argv: ["gate", "remove", id, ...force ? ["--force"] : []] };
  }
  return null;
};

// plugins/claude/hooks/gate-result.mjs
var missingDistMessage = (label, installer = "plugins/claude/install.sh") => `agentic-workflow: can't run the "${label}" gate \u2014 the plugin is not built (mcp-server/dist/server.js is missing). Run ${installer}, then retry.`;
var decideGateOutcome = ({ distExists, spawnError, status, stdout }, label, installer) => {
  if (!distExists) return { action: "block", message: missingDistMessage(label, installer), ok: false };
  if (spawnError || status === null || status === void 0) return { action: "pass" };
  let parsed = null;
  try {
    const last = (stdout || "").trim().split("\n").filter(Boolean).pop();
    parsed = last ? JSON.parse(last) : null;
  } catch {
    parsed = null;
  }
  if (parsed && typeof parsed.message === "string") {
    return { action: "block", message: parsed.message, ok: parsed.ok === true };
  }
  if (status !== 0) return { action: "pass" };
  return { action: "block", message: `Gate ${label} done.`, ok: true };
};

// plugins/claude/hooks/src/dialect.mjs
var DIALECTS = {
  claude: {
    stageMarkerFile: ".stage.json",
    // Mirrors core's `stageEvidenceFile(host)`; per host for the same reason the
    // marker is (one host's session must never write into another's ledger).
    evidenceFile: ".stage-evidence.json",
    // Claude Code surfaces plugin MCP tools under a second, plugin-bundled
    // alias; Qwen has only the one registration.
    verdictAliases: "mcp__agentic-workflow__workflow_verdict or, plugin-bundled, mcp__plugin_agentic-workflow_agentic-workflow__workflow_verdict",
    bash: ["Bash"],
    write: ["Edit", "Write", "NotebookEdit"],
    // The inspection tools whose target path is recorded as check-stage evidence
    // (hooks/src/evidence.mjs). Read-only by construction — a write tool's path
    // is not evidence of having *looked* at anything.
    read: ["Read", "Grep", "Glob"],
    spawnTool: "Task tool",
    // Whether the host's spawn tool takes a per-call model. False on Qwen: the
    // model is baked into the installed agent file, so telling the orchestrator
    // to "set `model`" would name a parameter that does not exist.
    conveysSpawnModel: true,
    // The tool names that spawn a subagent — read by the PreToolUse model stamp
    // AND by the spawn-stage guard. `Task` was renamed `Agent` in Claude Code
    // 2.1.63 and is still accepted as an alias, so both are matched: a rename
    // that silently stopped matching would disable the model binding and the
    // stage guard without failing anything.
    spawn: ["Agent", "Task"],
    // What the host prepends to a plugin agent's name in `subagent_type`
    // (`agentic-workflow:workflow-build`). Stripped before the name is checked
    // against the agents this plugin ships.
    agentPrefixes: ["agentic-workflow:", "mcp__plugin_agentic-workflow_agentic-workflow__"],
    installer: "plugins/claude/install.sh"
  },
  qwen: {
    stageMarkerFile: ".stage-qwen.json",
    evidenceFile: ".stage-evidence-qwen.json",
    verdictAliases: "mcp__agentic-workflow__workflow_verdict",
    bash: ["run_shell_command"],
    write: ["write_file", "edit", "replace", "notebook_edit"],
    read: ["read_file", "read_many_files", "search_file_content", "glob"],
    spawnTool: "`agent` tool",
    conveysSpawnModel: false,
    // Qwen spawns a subagent with the `agent` tool, passing the bare agent name
    // as `subagent_type` (docs/qwen.md). This list was empty while the model
    // stamp was its only reader — `conveysSpawnModel: false` stops that hook
    // before it looks at a tool name — but the spawn-stage guard reads it too and
    // is NOT gated by that flag, so an empty list would silently disable the
    // guard on this host.
    spawn: ["agent"],
    agentPrefixes: [],
    installer: "./install.sh qwen"
  }
};
var KNOWN_HOSTS = Object.keys(DIALECTS);
var hostFor = (env = process.env) => {
  const raw = env.AGENTIC_WORKFLOW_HOST || void 0;
  if (raw === void 0) return "claude";
  return raw in DIALECTS ? raw : null;
};
var dialectFor = (host) => host && host in DIALECTS ? DIALECTS[host] : null;

// plugins/claude/hooks/src/emit.mjs
var exitAfterWrite = (stream, payload, code) => {
  stream.write(payload, () => process.exit(code));
};

// plugins/claude/hooks/verb-slice.mjs
import fs from "node:fs";
import path from "node:path";
var MARKER = /^<!--\s*(\/?)aw:verb\s+([a-z][a-z0-9|-]*)\s*-->$/;
var normalize = (verb) => String(verb ?? "").trim().toLowerCase() || null;
var tagLines = (body) => {
  const tagged = [];
  let open;
  let block2 = 0;
  for (const text of body.split("\n")) {
    const marker = MARKER.exec(text.trim());
    if (marker) {
      const [, closing, names] = marker;
      if (closing) {
        if (open !== names) return null;
        open = void 0;
      } else {
        if (open !== void 0) return null;
        open = names;
        block2 += 1;
      }
      continue;
    }
    tagged.push({ text, verbs: open === void 0 ? null : open.split("|"), block: open === void 0 ? null : block2 });
  }
  return open === void 0 ? tagged : null;
};
var sliceForVerb = (body, verb) => {
  const tagged = tagLines(body);
  const wanted = normalize(verb);
  if (!tagged || !wanted) return null;
  const kept = tagged.filter((line) => line.verbs?.includes(wanted));
  if (kept.length === 0) return null;
  const parts = [];
  let prevBlock;
  for (const line of kept) {
    if (prevBlock !== void 0 && line.block !== prevBlock) parts.push("");
    parts.push(line.text);
    prevBlock = line.block;
  }
  return parts.join("\n").replace(/\n{3,}/g, "\n\n").trim();
};
var verbContext = (pluginRoot, verb) => {
  const wanted = normalize(verb);
  if (!wanted) return null;
  let body;
  try {
    body = fs.readFileSync(path.join(pluginRoot, "verbs", "engineering.md"), "utf8");
  } catch {
    return null;
  }
  const slice = sliceForVerb(body, wanted) ?? sliceForVerb(body, "unknown");
  if (!slice) return null;
  return [
    `VERB INSTRUCTIONS \u2014 /agentic-workflow:engineering ${wanted}`,
    "",
    "This is the authoritative procedure for the verb you were asked to run.",
    "The command body you received is only the router. Follow this block, and do",
    "not act on any other verb's description.",
    "",
    slice
  ].join("\n");
};

// plugins/claude/hooks/gate-command.mjs
var read = () => new Promise((resolve) => {
  let s = "";
  process.stdin.on("data", (c) => s += c).on("end", () => resolve(s));
});
var passThrough = () => process.exit(0);
var augment = (message) => {
  exitAfterWrite(process.stdout, JSON.stringify({ hookSpecificOutput: { hookEventName: "UserPromptSubmit", additionalContext: message } }), 0);
};
var block = (message) => {
  exitAfterWrite(
    process.stdout,
    JSON.stringify({
      decision: "block",
      reason: message,
      hookSpecificOutput: { hookEventName: "UserPromptSubmit", additionalContext: message }
    }),
    0
  );
};
var main = async () => {
  let input = {};
  try {
    input = JSON.parse(await read());
  } catch {
    return passThrough();
  }
  const prompt = input.prompt ?? input.user_input ?? input.userInput ?? "";
  const cwd = input.cwd || process.cwd();
  if (typeof prompt !== "string" || !prompt) return passThrough();
  const pluginRoot = process.env.AGENTIC_WORKFLOW_PLUGIN_ROOT || process.env.CLAUDE_PLUGIN_ROOT || path2.resolve(path2.dirname(fileURLToPath(import.meta.url)), "..");
  const injectVerb = () => {
    const context = verbContext(pluginRoot, verbFor(prompt));
    return context ? augment(context) : passThrough();
  };
  const dispatch = gateArgsFor(prompt);
  if (!dispatch) return injectVerb();
  if (dispatch.usage) return block(dispatch.usage);
  const args = dispatch.argv;
  const label = args.slice(1).join(" ");
  const serverJs = path2.join(pluginRoot, "mcp-server", "dist", "server.js");
  const distExists = fs2.existsSync(serverJs);
  const res = distExists ? spawnSync("node", [serverJs, ...args], {
    cwd,
    encoding: "utf8",
    env: { ...process.env, AGENTIC_WORKFLOW_DIR: process.env.AGENTIC_WORKFLOW_DIR ?? cwd }
  }) : {};
  const outcome = decideGateOutcome(
    { distExists, spawnError: res.error, status: res.status, stdout: res.stdout },
    label,
    dialectFor(hostFor())?.installer
  );
  if (outcome.action === "pass") return injectVerb();
  const message = outcome.message || `Gate ${label} ${outcome.ok ? "done" : "failed \u2014 see the backlog"}.`;
  if (dispatch.continueTurn && outcome.ok) {
    const context = verbContext(pluginRoot, verbFor(prompt), cwd);
    return augment(context ? `${message}

${context}` : message);
  }
  return block(message);
};
main();
