#!/usr/bin/env node
// GENERATED by scripts/build-hooks.mjs from hooks/src/ — do not edit by hand.

// plugins/claude/hooks/inject-ado-pat.mjs
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
var read = () => new Promise((resolve) => {
  let s = "";
  process.stdin.on("data", (c) => s += c).on("end", () => resolve(s));
});
var shellSingleQuote = (s) => `'${s.replace(/'/g, `'\\''`)}'`;
var userConfigPath = () => {
  const env = process.env.AGENTIC_WORKFLOW_USER_CONFIG;
  if (env !== void 0) return env === "" ? null : env;
  const home = os.homedir();
  if (!home) return null;
  const xdg = process.env.XDG_CONFIG_HOME;
  const configHome = xdg && xdg.trim() ? xdg : path.join(home, ".config");
  const primary = path.join(configHome, "agentic-workflow", "agentic-workflow.json");
  if (fs.existsSync(primary)) return primary;
  const legacy = path.join(home, ".agentic-workflow.json");
  if (fs.existsSync(legacy)) return legacy;
  return primary;
};
var readPat = (file) => {
  if (!file) return void 0;
  try {
    const cfg = JSON.parse(fs.readFileSync(file, "utf8"));
    if (cfg && cfg.ado && typeof cfg.ado.pat === "string" && cfg.ado.pat) return cfg.ado.pat;
  } catch {
  }
  return void 0;
};
var notice = (text) => {
  process.stdout.write(
    JSON.stringify({ hookSpecificOutput: { hookEventName: "SessionStart", additionalContext: text } }) + "\n"
  );
};
var main = async () => {
  if (process.env.AZURE_DEVOPS_EXT_PAT) return;
  const envFile = process.env.CLAUDE_ENV_FILE;
  if (!envFile) {
    let input2 = {};
    try {
      input2 = JSON.parse(await read());
    } catch {
    }
    const cwd2 = input2.cwd || process.cwd();
    const configured = readPat(path.join(cwd2, ".agentic-workflow.json")) ?? readPat(userConfigPath());
    if (configured) {
      notice(
        "agentic-workflow: an `ado.pat` is configured, but this host provides no session env-file channel to inject it (that is Claude Code only). Export AZURE_DEVOPS_EXT_PAT in your shell before starting the session, or the Azure DevOps sitters will fail to authenticate."
      );
    }
    return;
  }
  try {
    if (!fs.statSync(envFile).isFile()) return;
  } catch {
    return;
  }
  let input = {};
  try {
    input = JSON.parse(await read());
  } catch {
  }
  const cwd = input.cwd || process.cwd();
  const pat = readPat(path.join(cwd, ".agentic-workflow.json")) ?? readPat(userConfigPath());
  if (!pat) return;
  try {
    fs.appendFileSync(envFile, `export AZURE_DEVOPS_EXT_PAT=${shellSingleQuote(pat)}
`);
  } catch {
  }
};
main();
